- name: deploy the gisdev software stack
  hosts: localhost
  connection: local
  user: ubuntu
  sudo: true

  tasks:

    - name: Get aptitude for upgrade
      apt: pkg=aptitude state=present

    - name: Safe system upgrade via aptitude
      apt: upgrade=safe

    - name: ensure repository key is installed
      command: sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

    - name: ensure docker registry is available
      apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present

    - name: install base packages
      apt: pkg={{item}} state=present update_cache=yes cache_valid_time=604800
      with_items:
        - sysstat
        - htop
        - docker-engine
        - python-pip

    - service: name=docker state=restarted

    - name: Install global python requirements
      pip: name={{item}} state=present
      with_items:
        - docker-compose
