web:
   build: ./web
   container_name: xo-mybb-web-prod
   hostname: mybb-web
   ports:
      - "80:80"
   volumes:
      - /home/mybb/html:/var/www/html
   links:
      - db:mysql
db:
   build: ./db
   container_name: xo-mybb-db-prod
   hostname: mybb-db
   ports:
      - 3306:3306
   environment:
      - MYSQL_DB=mybb
      - MYSQL_USER=911labs
      - MYSQL_PASS=911labs
